allow-other: false
logging:
    type: syslog
libfuse:
    attribute-expiration-sec: 240
    entry-expiration-sec: 240
    negative-entry-expiration-sec: 120
file_cache:
    path: /mnt/azcache/haoling
    timeout-sec: 120
azstorage:
    account-name: xinzhanginterns # TO BE FILLED
    endpoint: https://xinzhanginterns.blob.core.windows.net   # TO BE FILLED
    container: jiewu  # TO BE FILLED
    mode: sas
    sas: ?sv=2023-01-03&st=2024-11-27T03%3A02%3A36Z&se=2024-12-03T03%3A02%3A00Z&skoid=c275b492-fed2-47ef-8704-1bb10e68fcf2&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2024-11-27T03%3A02%3A36Z&ske=2024-12-03T03%3A02%3A00Z&sks=b&skv=2023-01-03&sr=c&sp=racwdxltf&sig=lNZS14iL13QSIUCLw1Aro%2FNqVZmNBnUg072a2L6AXT4%3D
    update-md5: false
    validate-md5: false
    virtual-directory: true
    max-results-for-list: 0
    disable-compression: false
    telemetry: ""
    honour-acl: false
components:
    - libfuse
    - file_cache
    - azstorage
